### PR TITLE
Replaces the steam.styles to use a file that fixes notification issues on Wayland

### PR DESCRIPTION
**Pull request by orowith2os**
On Wayland, Steam notifs show blacked out. This file fixes that. Don't merge it right away, as it completely replaces the file. Maybe make it a patch instead?

### CODE REVIEW

**Comment by tkashkin** [comment]
I haven't changed the notification styles yet so that's probably the reason. This skin tries to `include` the default `steam.styles` to make unstyled controls use the default styles for now but I guess that didn't help in this case.

I'll close this PR and look into notifications later.

Open new issues if you notice something broken, preferably with screenshots and/or steps to reproduce.

**Comment by orowith2os** [comment]
The file I included is unrelated to the Adwaita skin, it's an issue with the upstream Steam client as well. I'm just submitting this so you can take the necessary bits to get it to work properly on Wayland

**Comment by orowith2os** [comment]
Something else to note, an issue IS open upstream, this would just allow it to function before that's resolved.

**Comment by tkashkin** [comment]
I've added some styles for notifications in 075092d, maybe it's fixed now. I will need screenshots and reproduction steps if it's still not fixed.

**Comment by orowith2os** [comment]
That commit seems to fix it. I will do some more testing to make sure it's all working, but no issues so far.

**Comment by orowith2os** [comment]
More testing has been done, and the issue is still there. [This Reddit post](https://www.reddit.com/r/swaywm/comments/sdfi38/steam_notifications_blacked_out/) may help on getting it worked out. All I have to say to reproduce it is use Wayland, and have a few notifications show up. The notifications will show as a black box.

**Comment by tkashkin** [comment]
I've disabled the notification animations as was suggested by the post you've linked, try again and see if it helped.

**Comment by orowith2os** [comment]
Yep, that's working now. Thanks for making the required changes.

**Pull request closed without merging**
