### PR TITLE
Support New UI

### PR DESCRIPTION
**Pull request by Foldex**
Figured I might as well open it.

TODO:
- [x] Top/Bottom Bars
- [x] Overlay
- [x] Notifications
- [x] Settings
- [x] Game Properties
- [x] Add Non-Steam Game
- [x] Product Activation
- [x] Recent Players
- [x] Game Servers
- [x] Screenshots
- [x] About Steam
- [x] System Info

### CODE REVIEW

**Comment by Foldex** [comment]
As it turns out, we can just use good old chrome remote debugging to inspect the new overlay.

Instructions:
1. Ensure nothing is running on your machine that uses port `8080` (Syncthing, etc)
2. Launch steam with the `-cef-enable-debugging` argument e.g. `steam -cef-enable-debugging`
3. Visit [Chrome Inspect](chrome://inspect/#devices) in your Chromium based browser
4. Under `Discover network targets`, make sure `localhost:8080` is present
5. Steam entries should start showing up

As a side note: It seems [SFP](https://github.com/PhantomGamers/SFP) and [Millenium](https://github.com/ShadowMonster99/millennium-steam-patcher) are already using remote debugging to regain lost functionality via injection. While I'm sure the abuse of debugging features to enable arbitrary code injection has some attached implications, figured it's at least worth noting here.

**Comment by IceDBorn** [comment]
Can you add a web extra for the notification's location? I've seen a lot of people editing steam.styles to change the location.

**Comment by Foldex** [comment]
> Can you add a web extra for the notification's location? I've seen a lot of people editing steam.styles to change the location.

`steam.styles` doesn't exist anymore. So I don't think it'd be possible, barring client hackery.

The new UI deals with hover elements like context menus/tooltips/notifications by compositing tiny webpages at specific locations. All CSS has control over is the elements within that page, not where the page itself is placed. Trying to move elements past where they spawn just winds up cutting them off.

image

**Comment by Foldex** [comment]
<details><summary>Overview</summary>

image
</details> 
<details><summary>Notification</summary>

image
</details> 

Added Initial Support for the In-Game Overlay and Notifications, probably missing stuff but it's just a first pass.

Some random notes:
- New UI means we can now round the corners of Steam's Main Window. Unfortunately this doesn't seem to be possible with pop up dialogs, chat, or embedded dialogs inside the ingame overlay. Shrug.
- The move off VGUI does mean we can put #45 to rest, Variable fonts work fine.
- I've added Web Extras to [hide the bottom bar](https://github.com/Foldex/Adwaita-for-Steam/blob/beta/web/extras/bottombar/hide_bar.css) and to [disable rounded corners](https://github.com/Foldex/Adwaita-for-Steam/blob/beta/web/extras/general/no_rounded_corners.css).

**Comment by Foldex** [comment]
- Server Browser support
- Product Activation support
- System Info support
- Recent Players support
- Added Web Extra for [dot style window controls](https://github.com/Foldex/Adwaita-for-Steam/blob/beta/web/extras/windowcontrols/dots.css)

image

**Comment by Caliel666** [comment]
hey, sorry if you already know about this, but the tittle bar off some of the "apps" in the overlay aren't correct:
image

and before these new commits since 2 weeks ago you could use the buttons in the tittle bar of the notes app, even though the buttons weren't in the spot you needed to click it worked, but now you can't interact with it at all, other apps works fine tho

**Comment by Foldex** [comment]
>the tittle bar buttons of some of the "apps" in the overlay aren't correct:

image

Thanks for letting me know, those icons should be fixed now.

Also added a Web Extra for [hiding the url bar](https://github.com/Foldex/Adwaita-for-Steam/blob/beta/web/extras/topbar/hide_url.css), since apparently that option is gone from the beta.

**Comment by Foldex** [comment]
Since it seems like the beta might remain a beta for a good while longer, I've added support for installing from this branch to AdwSteamGtk.

image

Release should hit flathub in a few hours.

**Comment by Foldex** [comment]
Game Properties are back to looking remotely Adwaita-ish:

<details><summary>Before</summary>
<p>

ss-2023-05-31_20:05:33
ss-2023-05-31_20:06:12
ss-2023-05-31_20:06:37

</p>
</details> 

<details><summary>After</summary>
<p>

ss-2023-05-31_20:07:11
ss-2023-05-31_20:07:17
ss-2023-05-31_20:07:25

</p>
</details> 

There are a few sections that I'm unable to make look like a properly attached Adwaita Preference Row.
Would be easy if they belonged to the same parent node, but unfortunately they belong to entirely separate sections.
Gonna hit it with the old  "It's probably good enough".

<details><summary>Images</summary>
<p>

image

image

</p>
</details>

**Comment by Foldex** [comment]
Install Dialog done:
image

Overlay List Mode done:
image

Steam Settings is partially cleaned up, though it's not quite Adwaita.
Due to how many sub layouts are used within this dialog, most of which using generic classes, getting things to look like Adwaita Preference Rows is likely going to be a pain:
image

For those who don't like the Adwaita styled Top Bar, added a web extra that reverts to the [Original Steam Bar](https://github.com/Foldex/Adwaita-for-Steam/blob/beta/web/extras/topbar/vanilla_bar.css):
image

**Comment by Blisterexe** [comment]
apologies if you already know this, but the steam close button (middle) does not look like it should, at least compared to native (themed using gradience) gtk4 applications
Screenshot from 2023-06-10 19-09-29
Screenshot from 2023-06-10 19-09-40

**Comment by Foldex** [comment]
> the steam close button (middle) does not look like it should

Latest Beta Client made some changes to the Window Controls.
Should be fixed by https://github.com/tkashkin/Adwaita-for-Steam/pull/150/commits/ace865de9abc01e9fcee13284ce58be67a64c4cb
image

**Comment by Foldex** [comment]
@tkashkin 
[New UI is out of Beta](https://store.steampowered.com/news/app/593110/view/3687931965598906184), so marking this as ready to review.

**Pull request merged**
