### PR TITLE
Add in-game overlay styling

### PR DESCRIPTION
**Pull request by PiiNGPooNG**
Adds styling for the in-game overlay that resembles popovers from Gnome such as the screenshot tool.

Note: Left out :active/:selected styling for the buttons, because some of them don't seem to do anything for those pseudoclasses

### CODE REVIEW

**Comment by tkashkin** [comment]
Looks great, thanks. I have a few suggestions:

###### Icon labels

Some icons are not immediately obvious and there are no tooltips unfortunately.
Text labels like the ones in the GNOME screenshot popover would be ideal.

You can try to reuse some of the short labels.
Alternatively add text as images if there are no suitable labels or if it's not possible to place/align them correctly.
Unlocalized text should still be better than no text at all, and it can be localized later by creating multiple image variants to be switched by patching the skin.

###### Spacing

The spacing between the buttons seems to be a bit larger than in the GNOME screenshot popover. Very minor issue.

###### Achievements, guides, friends

Achievements, guides and friends windows from the original overlay are useful sometimes, perhaps they should be implemented somehow.

---

Have you found a way to access the VGUI debugger in the overlay or is it not possible?

**Comment by PiiNGPooNG** [comment]
###### Icon labels
I'll see what's possible with the labels. I think it will likely have to be images though.

###### Spacing
Will adjust.

###### Achievements, guides, friends
The panel elements are what's used in the popover, so extending the information displayed would be tricky without just completely detaching them

Why I decided to remove the guides panel and parts of the other panels:
- The full friends list is accessed in just 1 click
- The most recent achievement got info can sometimes be useful. Kept it out mainly for simplicity, and because the info can still be somewhat found within the achievements menu
-  I usually don't open guides from the previews, but instead navigate to the guides page to be able to search/filter. That page is a tab on the community hub, so you get there in 2 clicks

The skin Fluent for Steam adds the progress bar for achievements like this:
Screenshot from 2022-09-27 19-45-52
Should be possible to do something similar, but wasn't sure if it fits the style.

---
I could't find a way to access the VGUI debugger in the overlay unfortunately. I've been looking at the default layout as well as the Metro and Fluent skins to figure out what is what.

**Comment by PiiNGPooNG** [comment]
Pushed a version with image labels to a separate [branch](/PiiNGPooNG/Adwaita-for-Steam/tree/labeltest).

**Comment by tkashkin** [comment]
Labels look good. A few more suggestions:

1. Text looks slightly too close to the icons, I think it will look a bit better if moved a couple of pixels down.
2. The label image height should probably be increased to 20-24px to make sure it's possible to make the labels readable in all languages. CJK languages usually require more height. (This should also solve the first problem if text is centered)

I also have a couple of ideas for the layout, not sure what would be better:

1. Buttons can be reordered and possibly separated.
I would expect something like `Browser|Friends,Players?|Community,Achievements,...|Controller,Settings`.
2. Another idea is to move some of the buttons to a second row.
For example `Settings` and `Controller` buttons could be placed like the `Show pointer` button in the GNOME screenshoot tool.
`Browser` and maybe `Friends` could also be moved there, so the first row only contains the buttons related to the game (`Community`, `Achievements`, etc.) and everything else is in the second row.

**Comment by PiiNGPooNG** [comment]
There are some limitations with reordering the items.

`Friends` and `Players` are part of the same panel and share the same styling.

Same goes for `Browser` and `Settings`. Additionally, they are part of a separate overlay section entirely. My preferred order would've also been Browser first and Settings last, but when ordered like that the element containing the two covers up the rest of the buttons, making them unclickable.

I like the idea with the second row and using the small circular button style for that. I'll try out a layout with that idea.

**Comment by PiiNGPooNG** [comment]
Made a version with browser, settings and controller config on a second row. Pushed it to the [layouttest branch](/PiiNGPooNG/Adwaita-for-Steam/tree/layouttest).

**Comment by tkashkin** [comment]
Not bad. A couple of improvements more and I think it will be ready to merge:

1. Swap `Controller` and `Settings` buttons if possible.
2. Add a label for the `Browser` button and make it wider. This should balance both sides visually and make the `Browser` button a bit more noticeable.
3. Use a monospace font for the time label.

**Comment by PiiNGPooNG** [comment]
1. Sadly not possible due to reason stated above
2. Like this?
browserlabel
3. Just the time or also for the other 3 lines?

**Comment by tkashkin** [comment]
> Like this?

Yes, something like this seems to be fine, but you can keep it how it was if you think it looks weird.

> Just the time or also for the other 3 lines?

Just the time, because it updates each second and it's very noticeable when the digits change width and the whole label moves and resizes.

**Comment by PiiNGPooNG** [comment]
Made the adjustments and merged everything into master.

**Pull request merged**
