### PR TITLE
Web Full: Dialog & App Properties Fixes

### PR DESCRIPTION
**Pull request by Foldex**
[2022-10-14_23-39-02-[00.00.000-00.29.909].webm](https://user-images.githubusercontent.com/47908676/195967437-7a926bb9-a279-4941-a15d-540581e8b045.webm)

Mostly focused on theming the app properties window, but some rulesets are fairly general to Dialogs. I haven't noticed any breakages, and they seem to be applying fine in other dialogs like Friends List settings (which I believe is the last dialog left to do).

### CODE REVIEW

**Comment by Foldex** [comment]
Added Friend Settings.
Unfortunately this dialog uses a different widget of two separate buttons for some toggles rather than a single checkbox or slider. Don't think I can get it looking like the other more Adwaita-like switches.

buttons
switches

**Comment by tkashkin** [comment]
Sorry for not replying sooner, didn't have time to review this.

A few issues to be fixed before it's ready to merge:

1. All rows should ideally have the same height. Make them 50px tall to match how rows look in VGUI dialogs.
Rows with very long subtitles can be taller if needed, see Leaflet page in Adwaita Demo for example.
2. Group rows if possible and remove the margins between them. Separate them with 1px bottom border or 1px margin.
Only the first and the last row in a group should be rounded. Should be doable using `:first-child` and `:last-child` selectors.
3. Match font sizes, weights, styles, and colors to how they look in `libadwaita`. Use [GTK Inspector](https://docs.gtk.org/gtk4/running.html#interactive-debugging) in Adwaita Demo app to check styles easier.

**Comment by IceDBorn** [comment]
They added this option in the menus

image

**Comment by Foldex** [comment]
>  Only the first and the last row in a group should be rounded. Should be doable using `:first-child` and `:last-child` selectors.

Was a bit of a pain since some dialogs use mixed classes dumped into a single div. There is one section under `Size & Scaling` in the friends list settings I don't think I can completely finagle because of this though.

> They added this option in the menus

Unfortunately I don't seem to have any games that have that option, so I'm unable to test the launch options.

@tkashkin 
Thoughts?

<details>
<summary>Preview</summary>

ss-2023-01-15_10:45:27
ss-2023-01-15_10:45:42
ss-2023-01-15_10:46:08
</details>

**Pull request merged**
